In [30]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd
from selenium.webdriver.common.by import By

## Scraping table on internet service providers (whistleout.com)

In [ ]:
# Set up Selenium WebDriver
driver3 = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

# Go to the target website
url_internet = "https://www.whistleout.com/Internet/Providers"
driver3.get(url_internet)

# Wait for the page to load fully
time.sleep(10)

try:
    # Locate the main content area with the table or listings
    table = driver3.find_element(By.CLASS_NAME, "tab-content")

    # Extract rows (in this case 'pad-r-4' might be used to locate plan data)
    rows = table.find_elements(By.CLASS_NAME, 'pad-r-4')

    # Create lists to store extracted data
    plans_numbers = []
    internet_categories = []
    carriers = []
    table_internet_data = []


    for row in rows:
        table_data = {}
        # Extract the text part with the name of the carrier
        carrier = row.find_element(By.TAG_NAME, 'h2')
        carrier = carrier.text
        carriers.append(carrier)
        table_data['Carrier'] = carrier
                                    
        # Extract the text part with the number of plans
        browse = row.find_element(By.TAG_NAME, 'b')
        plans_number = browse.text.split(" ")[1]  # Extract second word from the sentence "browse xxx plans"
        plans_numbers.append(plans_number)
        table_data['Plans available'] = plans_number

        # Extract the internet category (button text)
        list_within_list = []
        cat_per_carrier = row.find_elements(By.TAG_NAME, 'p')
        for p_tag in cat_per_carrier:
            internet_cat = p_tag.find_elements(By.CLASS_NAME, 'btn-info')
            for cat in internet_cat:
                internet = cat.text
                list_within_list.append(internet)
        #internet_categories.append(list_within_list)
        #table_data['Internet Categories'] = internet_categories
        table_data['Internet Categories'] = ', '.join(list_within_list)

        table_internet_data.append(table_data)

finally:
    # Close the browser after scraping
    driver3.quit()

In [38]:
df_internet = pd.DataFrame(table_internet_data)
df_internet

,Carrier,Plans available,Internet Categories
0,Xfinity,128,"All, Fiber, Cable"
1,T-Mobile,4,Mobile Broadband
2,Spectrum,15,Cable
3,EarthLink,18,"All, Fiber, Mobile Broadband"
4,AT&T,6,"All, Fiber, Mobile Broadband"
5,Verizon,8,Mobile Broadband
6,Frontier,4,Fiber
7,Verizon Fios,6,Fiber
8,NOW,12,Mobile Broadband
9,Viasat,1,Satellite
10,Quantum,4,Fiber
11,Optimum,30,"All, Fiber, Cable"
12,Cox,25,"All, Fiber, Cable"
13,Metro by T-Mobile (MetroPCS),1,Mobile Broadband
14,Mediacom,12,Cable
15,WOW!,8,Cable
16,HughesNet,2,Satellite
17,Astound Broadband- Pacific Northwest,20,Fiber
18,Astound Broadband,168,"All, Fiber, Cable"
19,Ziply,4,Fiber
20,Astound Broadband- Texas,8,Fiber
21,Windstream,30,"All, Fiber, Cable"
22,Breezeline,4,Cable
23,Google Fiber,2,Fiber
24,Starlink,2,Satellite
25,Mercury Broadband,3,Fixed Wireless
26,CenturyLink,11,VDSL
27,Starry,5,Fixed Wireless
28,Wyyerd,5,Fiber
29,Armstrong,3,Cable
30,Rise Broadband,1,Fiber
31,Fidelity Communications,6,Cable
32,Brightspeed,4,Fiber
33,Ting,1,Fiber
34,Utah Broadband,3,Fiber
35,TDS,1,Cable
36,Sparklight,4,Cable
37,MCTV,4,Cable
38,Sonic,0,Fiber

In [54]:
#Adding fake carrier "Telco" from our Kaggle dataset
telco_row = pd.DataFrame({
    'Carrier': ['Telco'],
    'Plans available': [3],
    'Internet Categories': ['DSL, Cable'] })

# Concatenate the new row to the existing DataFrame
df_internet = pd.concat([df_internet, telco_row], ignore_index=True)

#Adding a carrier ID column
df_internet['Carrier_ID'] = range(1, len(df_internet) + 1)
df_internet

,Carrier,Plans available,Internet Categories,Carrier_ID
0,Xfinity,128,"All, Fiber, Cable",1
1,T-Mobile,4,Mobile Broadband,2
2,Spectrum,15,Cable,3
3,EarthLink,18,"All, Fiber, Mobile Broadband",4
4,AT&T,6,"All, Fiber, Mobile Broadband",5
5,Verizon,8,Mobile Broadband,6
6,Frontier,4,Fiber,7
7,Verizon Fios,6,Fiber,8
8,NOW,12,Mobile Broadband,9
9,Viasat,1,Satellite,10
10,Quantum,4,Fiber,11
11,Optimum,30,"All, Fiber, Cable",12
12,Cox,25,"All, Fiber, Cable",13
13,Metro by T-Mobile (MetroPCS),1,Mobile Broadband,14
14,Mediacom,12,Cable,15
15,WOW!,8,Cable,16
16,HughesNet,2,Satellite,17
17,Astound Broadband- Pacific Northwest,20,Fiber,18
18,Astound Broadband,168,"All, Fiber, Cable",19
19,Ziply,4,Fiber,20
20,Astound Broadband- Texas,8,Fiber,21
21,Windstream,30,"All, Fiber, Cable",22
22,Breezeline,4,Cable,23
23,Google Fiber,2,Fiber,24
24,Starlink,2,Satellite,25
25,Mercury Broadband,3,Fixed Wireless,26
26,CenturyLink,11,VDSL,27
27,Starry,5,Fixed Wireless,28
28,Wyyerd,5,Fiber,29
29,Armstrong,3,Cable,30
30,Rise Broadband,1,Fiber,31
31,Fidelity Communications,6,Cable,32
32,Brightspeed,4,Fiber,33
33,Ting,1,Fiber,34
34,Utah Broadband,3,Fiber,35
35,TDS,1,Cable,36
36,Sparklight,4,Cable,37
37,MCTV,4,Cable,38
38,Sonic,0,Fiber,39
39,Telco,3,"DSL, Cable",40

## Scraping table on best cell phone plans

In [31]:
# Set up Selenium WebDriver
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

# Go to the target website
url_cellphone = "https://www.whistleout.com/CellPhones/Guides/Best-cell-phone-plans"
driver.get(url_cellphone)

# Wait for the page to load fully
time.sleep(10)

# Locate the table
table = driver.find_element(By.CLASS_NAME, "table-condensed")

# Extract table rows from the tbody
rows = table.find_elements(By.TAG_NAME, 'tr')

# Create an empty list to store extracted data
table_data = []

# Iterate through the rows and extract data from the columns (td elements)
for row in rows:
    cells = row.find_elements(By.TAG_NAME,'td')
    if len(cells) > 0:
        carrier_name = cells[0].text.split("\n")[0]  # Extract carrier name
        plan_name = cells[0].text.split("\n")[1]     # Extract plan name
        price = cells[1].text                        # Extract price
        best_for = cells[2].text                     # Extract "best for" category
        plan_link = cells[3].find_element(By.TAG_NAME, 'a').get_attribute('href')  # Extract link to the plan
        
        # Append the data to the list as a dictionary
        table_data.append({
            'Carrier': carrier_name,
            'Plan': plan_name,
            'Price': price,
            'Best For': best_for,
            'Plan Link': plan_link
        })

# Close the browser after scraping
driver.quit()

In [32]:
df_cellphone_plans = pd.DataFrame(table_data)
df_cellphone_plans

,Carrier,Plan,Price,Best For,Plan Link
0,Visible,Visible+,$45/month,Value,https://www.whistleout.com/Transact?si=489&pai=3
1,Mint Mobile,Unlimited,$30/month,Lowest prices,https://www.whistleout.com/Transact?si=457&pai=3
2,US Mobile,Unlimited Premium,$88-176/month\n(2-4 lines),Family plan and\nperks,https://www.whistleout.com/Transact?si=420&pai=3
3,US Mobile,10GB By the Gig,$20/month,Single-line plan,https://www.whistleout.com/Transact?si=420&pai=3
4,T-Mobile,Go5G Plus,$90/month,Major carrier,https://www.whistleout.com/Transact?si=376&pai=3
5,Twigby,"Unlimited Talk, Text + 20GB Data",$10/month,Limited data,https://www.whistleout.com/Transact?pai=3&si=4...

In [55]:
#Adding a carrier ID column

carrier_mapping = dict(zip(df_internet['Carrier'], df_internet['Carrier_ID']))
#append on the carrier mapping dictionnary to add more carriers ID
carrier_mapping['Visible'] = 41
carrier_mapping['Mint Mobile'] = 42
carrier_mapping['US Mobile'] = 43
carrier_mapping['Twigby'] = 44

df_cellphone_plans['Carrier_ID'] = df_cellphone_plans['Carrier'].map(carrier_mapping)
df_cellphone_plans

,Carrier,Plan,Price,Best For,Plan Link,Carrier_ID
0,Visible,Visible+,$45/month,Value,https://www.whistleout.com/Transact?si=489&pai=3,41
1,Mint Mobile,Unlimited,$30/month,Lowest prices,https://www.whistleout.com/Transact?si=457&pai=3,42
2,US Mobile,Unlimited Premium,$88-176/month\n(2-4 lines),Family plan and\nperks,https://www.whistleout.com/Transact?si=420&pai=3,43
3,US Mobile,10GB By the Gig,$20/month,Single-line plan,https://www.whistleout.com/Transact?si=420&pai=3,43
4,T-Mobile,Go5G Plus,$90/month,Major carrier,https://www.whistleout.com/Transact?si=376&pai=3,2
5,Twigby,"Unlimited Talk, Text + 20GB Data",$10/month,Limited data,https://www.whistleout.com/Transact?pai=3&si=4...,44

## Scraping table on best mobile phone and internet bundles

In [33]:
driver2 = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

# Go to the target website
url_bundles = "https://www.whistleout.com/CellPhones/Guides/best-cell-phone-and-internet-bundles"
driver2.get(url_bundles)

# Wait for the page to load fully
time.sleep(10)

# Locate the table
table = driver2.find_element(By.CLASS_NAME, "table-condensed")

# Extract table rows from the tbody
rows = table.find_elements(By.TAG_NAME, 'tr')

# Create an empty list to store extracted data
table_bundles_data = []

# Iterate through the rows and extract data from the columns (td elements)
for row in rows:
    cells = row.find_elements(By.TAG_NAME,'td')
    if len(cells) > 0:
        carrier_name = cells[0].text  
        bundle_plan = cells[1].text    
        bundle_price = cells[2].text                       
        best_for = cells[3].text                   
        plan_link = cells[4].find_element(By.TAG_NAME, 'a').get_attribute('href')  # Extract link to the plan
        
        # Append the data to the list as a dictionary
        table_bundles_data.append({
            'Carrier': carrier_name,
            'Bundle plan': bundle_plan,
            'Price': bundle_price,
            'Best For': best_for,
            'Plan Link': plan_link
        })

# Close the browser after scraping
driver2.quit()

In [34]:
df_bundles = pd.DataFrame(table_bundles_data)
df_bundles

,Carrier,Bundle plan,Price,Best For,Plan Link
0,AT&T,Unlimited Extra EL w/\nInternet 300,Starting at $110.99/mo.,Overall,https://www.whistleout.com/Transact?pai=3&si=3...
1,T-Mobile,Magenta MAX w/\nT-Mobile 5G home,Starting at: $115/mo.,5G internet,https://www.whistleout.com/Transact?pai=2&si=3...
2,Cox Mobile,By the Gig w/\nPreferred 250,Starting at: $65/mo.,Pay-per-gig,https://www.whistleout.com/Transact?pai=3&si=5...
3,Spectrum Mobile,Unlimited data w/\nInternet 100,Starting at: $60/mo.,No-contract plans,https://www.whistleout.com/Transact?pai=3&si=4...
4,Xfinity Mobile,Unlimited Intro w/\nInternet Essentials,Starting at: $55/mo.,Cheap internet,https://www.whistleout.com/Transact?pai=3&si=4...
5,Optimum Mobile,Unlimited MAX w/\nOptimum 300,Starting at: $95/mo.,Internet perks,https://www.whistleout.com/Transact?pai=3&si=5...

In [53]:
df_bundles['Carrier']=df_bundles['Carrier'].str.replace(" Mobile","")

df_bundles['Carrier_ID'] = df_bundles['Carrier'].map(carrier_mapping)
df_bundles

,Carrier,Bundle plan,Price,Best For,Plan Link,Carrier_ID
0,AT&T,Unlimited Extra EL w/\nInternet 300,Starting at $110.99/mo.,Overall,https://www.whistleout.com/Transact?pai=3&si=3...,5
1,T-Mobile,Magenta MAX w/\nT-Mobile 5G home,Starting at: $115/mo.,5G internet,https://www.whistleout.com/Transact?pai=2&si=3...,2
2,Cox,By the Gig w/\nPreferred 250,Starting at: $65/mo.,Pay-per-gig,https://www.whistleout.com/Transact?pai=3&si=5...,13
3,Spectrum,Unlimited data w/\nInternet 100,Starting at: $60/mo.,No-contract plans,https://www.whistleout.com/Transact?pai=3&si=4...,3
4,Xfinity,Unlimited Intro w/\nInternet Essentials,Starting at: $55/mo.,Cheap internet,https://www.whistleout.com/Transact?pai=3&si=4...,1
5,Optimum,Unlimited MAX w/\nOptimum 300,Starting at: $95/mo.,Internet perks,https://www.whistleout.com/Transact?pai=3&si=5...,12

# You can also save it to a CSV file if needed
df.to_csv('cell_phone_plans.csv', index=False)

# Optional: Insert into SQL database (MySQL example below)
import pymysql

# Set up your database connection
db_conn = pymysql.connect(host="localhost", user="root", password="mysqlpassword", database="telecom")

# Create a cursor object
cursor = db_conn.cursor()

# Create a SQL insert query
insert_query = """INSERT INTO cell_phone_plans (Carrier, Plan, Price, BestFor, PlanLink)
                  VALUES (%s, %s, %s, %s, %s)"""

# Insert each row into the database
for row in table_data:
    cursor.execute(insert_query, (row['Carrier'], row['Plan'], row['Price'], row['Best For'], row['Plan Link']))

# Commit and close the database connection
db_conn.commit()
db_conn.close()

## Family plan options for specific carrier (T-Mobile)

In [ ]:
# Set up Selenium WebDriver
driver4 = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

# Go to the target website
url_tmobile = "https://www.whistleout.com/CellPhones/Reviews/t-mobile-cell-phone-plans-review"
driver4.get(url_tmobile)

# Wait for the page to load fully
time.sleep(10)

# Locate the table
tables = driver4.find_elements(By.CLASS_NAME, "table-condensed")
table = tables[1]

# Extract table rows from the tbody
rows = table.find_elements(By.TAG_NAME, 'tr')

# Create an empty list to store extracted data
tmobile_data = []

# Iterate through the rows and extract data from the columns (td elements)
for row in rows:
    cells = row.find_elements(By.TAG_NAME,'td')
       
    if len(cells) > 0:
        plan_name = cells[0].text  # Get the plan name
        
        # Get the multiline discount (this contains different options for each plan)
        multi_line = cells[1].text.split('\n')  # Split by newlines to handle each line
        total_price = cells[2].text.split('\n')  # Split prices by newlines

 
        # Now match each line option with its corresponding price
        for line_option, price_option in zip(multi_line, total_price):
            # Append each individual line and price with the plan name to the data
            tmobile_data.append({
                'Plan': plan_name,
                'Lines': line_option.split(':')[0].strip(),  # Clean up line option (e.g., "2 lines")
                'Price per Line': line_option.split(':')[1].strip(),  # Get the price per line
                'Total Monthly Price': price_option.strip()  # Get the total price for that line
            })


# Close the browser after scraping
driver4.quit()

In [39]:
df_tmobile = pd.DataFrame(tmobile_data)
df_tmobile

           Plan    Lines Price per Line Total Monthly Price
0    Essentials  2 lines       $45/line           $90/month
1    Essentials  3 lines       $30/line           $90/month
2    Essentials  4 lines       $25/line          $100/month
3    Essentials  5 lines       $24/line          $120/month
4       Magenta  2 lines       $60/line          $120/month
5       Magenta  3 lines    $46.67/line          $140/month
6       Magenta  4 lines       $40/line          $160/month
7       Magenta  5 lines       $36/line          $180/month
8   Magenta Max  2 lines        $70line          $140/month
9   Magenta Max  3 lines    $56.67/line          $170/month
10  Magenta Max  4 lines       $50/line          $200/month
11  Magenta Max  5 lines       $46/line          $230/month
12         Go5G  2 lines       $70/line          $140/month
13         Go5G  3 lines    $56.67/line          $140/month
14         Go5G  4 lines    $38.75/line          $155/month
15         Go5G  5 lines       $36/line          $180/month
16    Go5G Plus  2 lines       $75/line          $150/month
17    Go5G Plus  3 lines       $50/line          $150/month
18    Go5G Plus  4 lines    $46,25/line          $185/month
19    Go5G Plus  5 lines       $44/line          $220/month

In [43]:
#Adding a carrier ID column

df_tmobile['Carrier_ID'] = 2
df_tmobile

           Plan    Lines Price per Line Total Monthly Price  Carrier_ID
0    Essentials  2 lines       $45/line           $90/month           2
1    Essentials  3 lines       $30/line           $90/month           2
2    Essentials  4 lines       $25/line          $100/month           2
3    Essentials  5 lines       $24/line          $120/month           2
4       Magenta  2 lines       $60/line          $120/month           2
5       Magenta  3 lines    $46.67/line          $140/month           2
6       Magenta  4 lines       $40/line          $160/month           2
7       Magenta  5 lines       $36/line          $180/month           2
8   Magenta Max  2 lines        $70line          $140/month           2
9   Magenta Max  3 lines    $56.67/line          $170/month           2
10  Magenta Max  4 lines       $50/line          $200/month           2
11  Magenta Max  5 lines       $46/line          $230/month           2
12         Go5G  2 lines       $70/line          $140/month           2
13         Go5G  3 lines    $56.67/line          $140/month           2
14         Go5G  4 lines    $38.75/line          $155/month           2
15         Go5G  5 lines       $36/line          $180/month           2
16    Go5G Plus  2 lines       $75/line          $150/month           2
17    Go5G Plus  3 lines       $50/line          $150/month           2
18    Go5G Plus  4 lines    $46,25/line          $185/month           2
19    Go5G Plus  5 lines       $44/line          $220/month           2

## Export to CSV

In [49]:
df_cellphone_plans.to_csv('../data/clean/web_scraping/best_cell_phone_plans.csv', index=False)
df_bundles.to_csv('../data/clean/web_scraping/best_internet_mobile_bundles.csv', index=False)
df_internet.to_csv('../data/clean/web_scraping/internet_carriers_options.csv', index=False)
df_tmobile.to_csv('../data/clean/web_scraping/tmobile_family_plans.csv', index=False)

## Edit Telco Customer Churn table to add Carrier_ID for SQL database

In [56]:
telco_df = pd.read_csv("../data/clean/Telco_df_with_clusters_and_ID.csv")
telco_df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_cat,MonthlyCharges_cat,TotalCharges_cat,Cluster
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,Month-to-month,Yes,Electronic check,29.85,29.85,No,NaN,0-30,0-100,2
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,One year,No,Mailed check,56.95,1889.50,No,2-4 years,50-80,1000-2000,0
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0-1 year,50-80,100-500,0
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,One year,No,Bank transfer (automatic),42.30,1840.75,No,2-4 years,30-50,1000-2000,2
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0-1 year,50-80,100-500,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,One year,Yes,Mailed check,84.80,1990.50,No,1-2 years,80-100,1000-2000,0
7028,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,One year,Yes,Credit card (automatic),103.20,7362.90,No,over 4 years,over 100,over 5000,0
7029,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,Month-to-month,Yes,Electronic check,29.60,346.45,No,0-1 year,0-30,100-500,2
7030,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,Month-to-month,Yes,Mailed check,74.40,306.60,Yes,0-1 year,50-80,100-500,0
7031,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,over 4 years,over 100,over 5000,0

In [57]:
#add carrier_ID column
telco_df['Carrier_ID']=40
telco_df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_cat,MonthlyCharges_cat,TotalCharges_cat,Cluster,Carrier_ID
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,Yes,Electronic check,29.85,29.85,No,NaN,0-30,0-100,2,40
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,Mailed check,56.95,1889.50,No,2-4 years,50-80,1000-2000,0,40
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,Yes,Mailed check,53.85,108.15,Yes,0-1 year,50-80,100-500,0,40
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,Bank transfer (automatic),42.30,1840.75,No,2-4 years,30-50,1000-2000,2,40
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,Yes,Electronic check,70.70,151.65,Yes,0-1 year,50-80,100-500,0,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Mailed check,84.80,1990.50,No,1-2 years,80-100,1000-2000,0,40
7028,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,Credit card (automatic),103.20,7362.90,No,over 4 years,over 100,over 5000,0,40
7029,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,Yes,Electronic check,29.60,346.45,No,0-1 year,0-30,100-500,2,40
7030,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,Yes,Mailed check,74.40,306.60,Yes,0-1 year,50-80,100-500,0,40
7031,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Bank transfer (automatic),105.65,6844.50,No,over 4 years,over 100,over 5000,0,40

In [58]:
telco_df.to_csv('../data/clean/Telco_df_for_SQL.csv', index=False)